In [ ]:
import pandas as pd

Task 1

Read the Population dataset from the CSV file.

Hint:

● Use the pandas library.

● Display the first five rows.

● Check the shape and data types.

In [ ]:
population = pd.read_csv('/content/population.csv')

In [ ]:
population

           country  population
0    United States   331002651
1            China  1411778724
2            India  1380004385
3            Japan   125836021
4          Germany    83240525
5   United Kingdom    67886011
6           France    65273511
7            Italy    60461826
8           Canada    38005238
9        Australia    25687041
10          Brazil   212559417
11          Russia   145934462
12     South Korea    51780579
13           Spain    46754778
14          Mexico   128932753
15       Indonesia   273523615
16    Saudi Arabia    34813871
17          Turkey    84339067
18    South Africa    59308690
19       Argentina    45195774
20     Netherlands    17441139
21     Switzerland     8654622
22          Sweden    10353442
23          Norway     5421241
24       Singapore     5850342

In [ ]:
population.head()

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525

In [ ]:
population.shape

(25, 2)

In [ ]:
population.dtypes

country       object
population     int64
dtype: object

Task 2

Read the GDP dataset from the Excel file.

Hint:

● Use the appropriate pandas function.

● Display column names and data types.

In [ ]:
gdp = pd.read_excel('/content/gdp.xlsx')

In [ ]:
gdp

           Country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000

In [ ]:
gdp.columns

Index(['Country', 'GDP'], dtype='object')

In [ ]:
gdp.dtypes

Country    object
GDP         int64
dtype: object

Task 3

Read the Internet Users dataset from the JSON file.

Hint:

● Use either the json module or pandas.

● Convert the data into a DataFrame.

In [ ]:
internet_users = pd.read_json('/content/internet_users.json')

In [ ]:
internet_users

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

In [ ]:
internet_users = pd.read_json('internet_users.json')
internet_users

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

Task 4

Read the Literacy Rate dataset from the XML file.

Hint:

● Use xml.etree.ElementTree or pandas.read_xml().

● Extract all required fields into a DataFrame.

In [ ]:
literacy_rate = pd.read_xml('/content/literacy_rate.xml')
literacy_rate

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

In [ ]:
literacy_rate = pd.read_xml('literacy_rate.xml')
literacy_rate

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

Task 5

Explore each dataset.

Find the following:

● Number of rows

● Number of columns

● Column names

● Data types

● Missing values

● Duplicate records

In [ ]:
#population
len(population) # no of rows

25

In [ ]:
len(population.columns) # no  of columns

2

In [ ]:
population.columns # column names

Index(['country', 'population'], dtype='object')

In [ ]:
population.dtypes

country       object
population     int64
dtype: object

In [ ]:
population.isnull().sum()# missing values

country       0
population    0
dtype: int64

In [ ]:
population.duplicated().sum()

np.int64(0)

In [ ]:
# gdp
len(gdp) # no of rows

25

In [ ]:
len(gdp.columns) # no  of columns

2

In [ ]:
gdp.columns # column names

Index(['Country', 'GDP'], dtype='object')

In [ ]:
gdp.dtypes

Country    object
GDP         int64
dtype: object

In [ ]:
gdp.isnull().sum()# missing values

Country    0
GDP        0
dtype: int64

In [ ]:
gdp.duplicated().sum()

np.int64(0)

In [ ]:
# internet_users
len(internet_users) # no of rows

25

In [ ]:
len(internet_users.columns) # no  of columns

2

In [ ]:
internet_users.columns # column names

Index(['country', 'internet_users'], dtype='object')

In [ ]:
internet_users.dtypes

country           object
internet_users     int64
dtype: object

In [ ]:
internet_users.isnull().sum()# missing values

country           0
internet_users    0
dtype: int64

In [ ]:
internet_users.duplicated().sum()

np.int64(0)

In [ ]:
#literacy_rate
len(literacy_rate) # no of rows

25

In [ ]:
len(literacy_rate.columns) # no  of columns

2

In [ ]:
literacy_rate.columns # column names

Index(['name', 'literacy_rate'], dtype='object')

In [ ]:
literacy_rate.dtypes

name              object
literacy_rate    float64
dtype: object

In [ ]:
literacy_rate.isnull().sum()# missing values

name             0
literacy_rate    0
dtype: int64

In [ ]:
literacy_rate.duplicated().sum()

np.int64(0)

Task 6

Rename columns wherever necessary so that all datasets have a common column
name for merging.

Hint:

● Example: Country → country

In [ ]:
gdp = gdp.rename(columns={'Country': 'country'})

In [ ]:
gdp

           country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000

In [ ]:
literacy_rate = literacy_rate.rename(columns={'name': 'country'})
literacy_rate

           country  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

Task 7

Convert the required columns into appropriate numeric data types.

In [ ]:
population["population"] = pd.to_numeric(
    population["population"], errors="coerce"
)
gdp["GDP"] = pd.to_numeric(gdp["GDP"], errors="coerce")
internet_users["internet_users"] = pd.to_numeric(
    internet_users["internet_users"], errors="coerce"
)
literacy_rate["literacy_rate"] = pd.to_numeric(
    literacy_rate["literacy_rate"], errors="coerce"
)

In [ ]:
population.dtypes

country       object
population     int64
dtype: object

In [ ]:
gdp.dtypes

country    object
GDP         int64
dtype: object

In [ ]:
internet_users.dtypes

country           object
internet_users     int64
dtype: object

In [ ]:
literacy_rate.dtypes

country           object
literacy_rate    float64
dtype: object

Task 8

Merge all four datasets into one DataFrame.

Hint:

● Use the common column (country)

● Choose an appropriate join method.

In [ ]:
merged = (
    population.merge(literacy_rate, on="country", how="inner")
    .merge(internet_users, on="country", how="inner")
    .merge(gdp, on="country", how="inner")
)

In [ ]:
merged

           country  population  literacy_rate  internet_users       GDP
0    United States   331002651           99.0       312000000  30500000
1            China  1411778724           97.2      1080000000  19230000
2            India  1380004385           77.7       850000000   4187000
3            Japan   125836021           99.0       118000000   4180000
4          Germany    83240525           99.0        79000000   4744000
5   United Kingdom    67886011           99.0        66000000   3839000
6           France    65273511           99.0        62000000   3211000
7            Italy    60461826           99.0        56000000   2420000
8           Canada    38005238           99.0        36000000   2250000
9        Australia    25687041           99.0        24000000   1880000
10          Brazil   212559417           93.2       181000000   2330000
11          Russia   145934462           99.7       125000000   2200000
12     South Korea    51780579           98.8        50000000   1800000
13           Spain    46754778           98.6        44000000   1710000
14          Mexico   128932753           95.4       102000000   1810000
15       Indonesia   273523615           96.0       212000000   1500000
16    Saudi Arabia    34813871           97.3        34000000   1100000
17          Turkey    84339067           96.7        69000000   1350000
18    South Africa    59308690           95.0        43000000    410000
19       Argentina    45195774           99.1        41000000    640000
20     Netherlands    17441139           99.0        17000000   1150000
21     Switzerland     8654622           99.0         8500000    940000
22          Sweden    10353442           99.0        10100000    650000
23          Norway     5421241          100.0         5300000    580000
24       Singapore     5850342           97.5         5600000    530000

Task 9
Create the following calculated columns:
1. Internet Penetration (%)
2. GDP Per Capita
Hint:
Round the calculated values to two decimal places.

In [ ]:
merged["internet_penetration (%)"] = (
    merged["internet_users"] / merged["population"] * 100
).round(2)

In [ ]:
merged["GDP_Per_Capita"] = (
    merged["GDP"] * 1000000 / merged["population"]
).round(2)

In [ ]:
merged

,country,population,literacy_rate,internet_users,GDP,GDP_Per_Capita,internet_penetration (%)
0,United States,331002651,99.0,312000000,30500000,92144.28,94.26
1,China,1411778724,97.2,1080000000,19230000,13621.11,76.50
2,India,1380004385,77.7,850000000,4187000,3034.05,61.59
3,Japan,125836021,99.0,118000000,4180000,33217.83,93.77
4,Germany,83240525,99.0,79000000,4744000,56991.47,94.91
5,United Kingdom,67886011,99.0,66000000,3839000,56550.68,97.22
6,France,65273511,99.0,62000000,3211000,49193.00,94.98
7,Italy,60461826,99.0,56000000,2420000,40025.25,92.62
8,Canada,38005238,99.0,36000000,2250000,59202.37,94.72
9,Australia,25687041,99.0,24000000,1880000,73188.66,93.43
10,Brazil,212559417,93.2,181000000,2330000,10961.64,85.15
11,Russia,145934462,99.7,125000000,2200000,15075.26,85.65
12,South Korea,51780579,98.8,50000000,1800000,34762.07,96.56
13,Spain,46754778,98.6,44000000,1710000,36573.80,94.11
14,Mexico,128932753,95.4,102000000,1810000,14038.33,79.11
15,Indonesia,273523615,96.0,212000000,1500000,5483.99,77.51
16,Saudi Arabia,34813871,97.3,34000000,1100000,31596.60,97.66
17,Turkey,84339067,96.7,69000000,1350000,16006.82,81.81
18,South Africa,59308690,95.0,43000000,410000,6912.98,72.50
19,Argentina,45195774,99.1,41000000,640000,14160.62,90.72
20,Netherlands,17441139,99.0,17000000,1150000,65936.06,97.47
21,Switzerland,8654622,99.0,8500000,940000,108612.48,98.21
22,Sweden,10353442,99.0,10100000,650000,62781.05,97.55
23,Norway,5421241,100.0,5300000,580000,106986.57,97.76
24,Singapore,5850342,97.5,5600000,530000,90592.99,95.72

Task 10

Create a SQLite database. Store the final merged dataset into a table named
‘country_statistics’

Hint:

● Use the sqlite3 library.

● Load the DataFrame using pandas.

In [ ]:
import sqlite3

In [ ]:
conn =sqlite3.connect("country_statistics.db")
merged.to_sql("country_statistics",conn,
              if_exists = "replace",
              index = False
              )
conn.close()

In [ ]:
conn = sqlite3.connect("country_statistics.db")

df = pd.read_sql("SELECT * FROM country_statistics", conn)

conn.close()

df

,country,population,literacy_rate,internet_users,GDP,GDP_Per_Capita,internet_penetration (%)
0,United States,331002651,99.0,312000000,30500000,92144.28,94.26
1,China,1411778724,97.2,1080000000,19230000,13621.11,76.50
2,India,1380004385,77.7,850000000,4187000,3034.05,61.59
3,Japan,125836021,99.0,118000000,4180000,33217.83,93.77
4,Germany,83240525,99.0,79000000,4744000,56991.47,94.91
5,United Kingdom,67886011,99.0,66000000,3839000,56550.68,97.22
6,France,65273511,99.0,62000000,3211000,49193.00,94.98
7,Italy,60461826,99.0,56000000,2420000,40025.25,92.62
8,Canada,38005238,99.0,36000000,2250000,59202.37,94.72
9,Australia,25687041,99.0,24000000,1880000,73188.66,93.43
10,Brazil,212559417,93.2,181000000,2330000,10961.64,85.15
11,Russia,145934462,99.7,125000000,2200000,15075.26,85.65
12,South Korea,51780579,98.8,50000000,1800000,34762.07,96.56
13,Spain,46754778,98.6,44000000,1710000,36573.80,94.11
14,Mexico,128932753,95.4,102000000,1810000,14038.33,79.11
15,Indonesia,273523615,96.0,212000000,1500000,5483.99,77.51
16,Saudi Arabia,34813871,97.3,34000000,1100000,31596.60,97.66
17,Turkey,84339067,96.7,69000000,1350000,16006.82,81.81
18,South Africa,59308690,95.0,43000000,410000,6912.98,72.50
19,Argentina,45195774,99.1,41000000,640000,14160.62,90.72
20,Netherlands,17441139,99.0,17000000,1150000,65936.06,97.47
21,Switzerland,8654622,99.0,8500000,940000,108612.48,98.21
22,Sweden,10353442,99.0,10100000,650000,62781.05,97.55
23,Norway,5421241,100.0,5300000,580000,106986.57,97.76
24,Singapore,5850342,97.5,5600000,530000,90592.99,95.72

#TASK 11
Verify that the data has been loaded successfully.

In [ ]:
df.head()

,country,population,literacy_rate,internet_users,GDP,GDP_Per_Capita,internet_penetration (%)
0,United States,331002651,99.0,312000000,30500000,92144.28,94.26
1,China,1411778724,97.2,1080000000,19230000,13621.11,76.50
2,India,1380004385,77.7,850000000,4187000,3034.05,61.59
3,Japan,125836021,99.0,118000000,4180000,33217.83,93.77
4,Germany,83240525,99.0,79000000,4744000,56991.47,94.91

### Data Analysis Using Pandas

In [ ]:
#List the Top 5 countries by GDP.

merged.nlargest(5,"GDP")[['country','GDP']]

         country       GDP
0  United States  30500000
1          China  19230000
4        Germany   4744000
2          India   4187000
3          Japan   4180000

In [ ]:
#List the Top 5 countries by population.

merged.nlargest(5,"population")[['country','population']]

          country  population
1           China  1411778724
2           India  1380004385
0   United States   331002651
15      Indonesia   273523615
10         Brazil   212559417

In [ ]:
# Calculate the average literacy rate.

merged['literacy_rate'].mean()

np.float64(97.248)

In [ ]:

# List all countries having a literacy rate greater than 90%.

merged[merged['literacy_rate']>90][['country','literacy_rate' ]]

           country  literacy_rate
0    United States           99.0
1            China           97.2
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

In [ ]:
# List all countries having an internet penetration greater than 70%.

merged[merged['internet_penetration (%)']>90][['country','internet_penetration (%)' ]]

           country  internet_penetration (%)
0    United States                     94.26
3            Japan                     93.77
4          Germany                     94.91
5   United Kingdom                     97.22
6           France                     94.98
7            Italy                     92.62
8           Canada                     94.72
9        Australia                     93.43
12     South Korea                     96.56
13           Spain                     94.11
16    Saudi Arabia                     97.66
19       Argentina                     90.72
20     Netherlands                     97.47
21     Switzerland                     98.21
22          Sweden                     97.55
23          Norway                     97.76
24       Singapore                     95.72

In [ ]:
# List the Top 5 countries by GDP per capita.

merged.nlargest(5, "GDP_Per_Capita")[["country","GDP_Per_Capita"]]

          country  GDP_Per_Capita
21    Switzerland       108612.48
23         Norway       106986.57
0   United States        92144.28
24      Singapore        90592.99
9       Australia        73188.66

In [ ]:
#calculate the total population represented in the dataset.
merged['population'].sum()

np.int64(4720039725)

In [ ]:
#8 Calculate the average internet penetration across all countries.

merged['internet_penetration (%)'].mean()

np.float64(89.6596)

In [ ]:
# Identify the country having the highest number of internet users.
merged.loc[merged["internet_users"].idxmax(),['country','internet_users']]

country                China
internet_users    1080000000
Name: 1, dtype: object

In [ ]:
#Find the correlation between Literacy Rate and Internet Penetration.
merged['literacy_rate'].corr(merged['internet_penetration (%)'])

np.float64(0.77279756813985)

##Data analysis using SQL

In [ ]:
# Display the Top 5 countries by GDP. using sqlite

conn=sqlite3.connect('country_statistics.db')

pd.read_sql("""
SELECT country, GDP
FROM country_statistics
ORDER BY GDP DESC
LIMIT 5
""", conn)

         country       GDP
0  United States  30500000
1          China  19230000
2        Germany   4744000
3          India   4187000
4          Japan   4180000

In [ ]:
#  Find the average literacy rate.

pd.read_sql("""
SELECT AVG(literacy_rate) AS
average_litracy_rate
from country_statistics
""", conn)

   average_litracy_rate
0                97.248

In [ ]:
# Display all countries having literacy rate above 90%

pd.read_sql(
    """
SELECT country, literacy_rate
FROM country_statistics
WHERE literacy_rate > 90
ORDER BY literacy_rate DESC
""",
    conn,
)

           country  literacy_rate
0           Norway          100.0
1           Russia           99.7
2        Argentina           99.1
3    United States           99.0
4            Japan           99.0
5          Germany           99.0
6   United Kingdom           99.0
7           France           99.0
8            Italy           99.0
9           Canada           99.0
10       Australia           99.0
11     Netherlands           99.0
12     Switzerland           99.0
13          Sweden           99.0
14     South Korea           98.8
15           Spain           98.6
16       Singapore           97.5
17    Saudi Arabia           97.3
18           China           97.2
19          Turkey           96.7
20       Indonesia           96.0
21          Mexico           95.4
22    South Africa           95.0
23          Brazil           93.2

In [ ]:
#Find the Top 5 countries with the highest internet penetration.

pd.read_sql(
    """
SELECT country, `internet_penetration (%)`
FROM country_statistics
ORDER BY `internet_penetration (%)` DESC
LIMIT 5
""",
    conn,
)

        country  internet_penetration (%)
0   Switzerland                     98.21
1        Norway                     97.76
2  Saudi Arabia                     97.66
3        Sweden                     97.55
4   Netherlands                     97.47

In [122]:
#Calculate the total population.

pd.read_sql(
    """
SELECT SUM(population) AS total_population
FROM country_statistics
""",
    conn,
)

   total_population
0        4720039725

In [124]:
# Find the country with the highest GDP per capita.
pd.read_sql(
    """
SELECT country, GDP_Per_Capita
FROM country_statistics
ORDER BY GDP_Per_Capita DESC
LIMIT 1
""",
    conn,
)

       country  GDP_Per_Capita
0  Switzerland       108612.48

In [130]:
#Export the final merged dataset as a CSV file.
merged.to_csv("country_statistics.csv", index=False)

In [128]:
# Sort the dataset in descending order of GDP per Capita and display the Top 10
#countries.
#Write a short summary (5–6 points) explaining your ETL process, including:
#● Data sources used
#●Data cleaning steps
#● Transformations performed
#● Database loading process
#● Key insights obtained from the analysis

In [129]:
top_10_gdp_capita = merged.sort_values(
    by="GDP_Per_Capita", ascending=False
).head(10)[["country", "GDP_Per_Capita"]]
display(top_10_gdp_capita)

           country  GDP_Per_Capita
21     Switzerland       108612.48
23          Norway       106986.57
0    United States        92144.28
24       Singapore        90592.99
9        Australia        73188.66
20     Netherlands        65936.06
22          Sweden        62781.05
8           Canada        59202.37
4          Germany        56991.47
5   United Kingdom        56550.68